backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "gallery"
    label: "Project Gallery"
    folder: "_galleries"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "clients"
    label: "Featured Clients"
    folder: "_clients"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Logo", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - label: Gallery
        name: gallery
        widget: list
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
  - label: "Page Content"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - {label: "Title (id)", name: title_id, widget: string}
          - {label: "Title (en)", name: title_en, widget: string}
          - {label: "Description (id)", name: desc_id, widget: markdown}
          - {label: "Description (en)", name: desc_en, widget: markdown}
      - label: "About Page"
        name: "company"
        file: "_data/company.yml"
        fields:
          - {label: "Description (id)", name: desc_id, widget: markdown}
          - {label: "Description (en)", name: desc_en, widget: markdown}
          - {label: "Visi (en)", name: visi_id, widget: markdown}
          - {label: "Visi (id)", name: visi_en, widget: markdown}
          - {label: "Misi (en)", name: misi_id, widget: markdown}
          - {label: "Misi (id)", name: misi_id, widget: markdown}
          - {label: "Team Desc (id)", name: team_id, widget: markdown}
          - {label: "Team Desc (en)", name: team_en, widget: markdown}
          - label: "Team Member"
            name: "member"
            widget: list
            fields:
              - {label: "Name", name: name, widget: string}
              - {label: "Quote", name: quote, widget: markdown}
          - {label: "Group Image", name: group, widget: image}
      - label: "Contact Page"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - {label: "Location", name: lokasi, widget: string}
          - {label: "Studio Hour", name: office_hour, widget: string}
          - {label: "Office Hour", name: office_hour, widget: string}
          - {label: "Facebook", name: office_hour, widget: string}
          - {label: "Instagram", name: office_hour, widget: string}
      - label: "Service Page"
        name: "service"
        file: "_data/sevice.yml"
        fields:
          - label: "Interior and  Civil Works"
            name: civil
            widget: list
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "Description", name: description, widget: markdown}
          - label: "Design and Build"
            name: build
            widget: list
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "Description", name: description, widget: markdown}
          - label: "Furnitur"
            name: furnitur
            widget: list
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "Description", name: description, widget: markdown}
          - label: "Mechanical and Electric"
            name: mechanical
            widget: list
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "Description", name: description, widget: markdown}
          - label: "Architecture"
            name: architecture
            widget: list
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "Description", name: description, widget: markdown}
          - label: "Artwork"
            name: art
            widget: list
            fields:
              - {label: "Image", name: image, widget: image}
              - {label: "Description", name: description, widget: markdown}